const router=require('express').Router()
const dashboardRoute =require('./dashboardRoute.route')
const authRoute=require('./auth/index') 
const adminRoute=require('./adminRoute/index')
const teacherRoute=require('./teacherRoute/index')
const teacherAuth=require('./teacherRoute/login.route')
const logoutRoute=require('./logout.route')
const adminAuth=require('./adminRoute/login.route')
router.use('/auth',authRoute)
router.use('/teacterAuth',teacherAuth)
router.use('/adminAuth' ,adminAuth)
router.use('/dashboard',dashboardRoute) 
router.use('/admin',adminRoute)
router.use('/teacher',teacherRoute)
router.use('/logout',logoutRoute)
// router.use('/admin',adminRoute)
module.exports=router;