const router=require('express').Router()
const dashboardRoute =require('./dashboardRoute.route')
const authRoute=require('./auth/index') 
const teacherAuth=require('./auth/teacherAuth/login.route')
const logoutRoute=require('./logout.route')
const adminAuth=require('./auth/adminRoute/login.route')
router.use('/auth',authRoute)
router.use('/teacterAuth',teacherAuth)
router.use('/adminAuth' ,adminAuth)
router.use('/dashboard',dashboardRoute) 
router.use('/logout',logoutRoute)
// router.use('/admin',adminRoute)
module.exports=router;